#!/usr/bin/env python3
"""Rebuild the registers from the artifacts that are actually on disk.

Two jobs, both mechanical:

1. **Artifact inventory** — hash and size every file under ``evidence/`` and write
   ``registry/experiments.json`` (protocol + artifact list). Nothing about a result is typed by hand;
   the site reads this file.
2. **Submission register** — build ``registry/submissions.json`` from the ``*-format-check.json``
   receipts written by ``scripts/build_submission.py``, so every SHA-256 and pixel count in the
   register is copied out of a receipt rather than retyped. The per-file narrative (role, caveat,
   slot status) is declared in ``SUBMISSIONS`` below and joined to the receipts by file name.

Legacy run-cache files (``--cache``) are copied into ``evidence/`` if that directory still exists;
in a fresh clone it does not, and every artifact is regenerated by the scripts named on the
validation page instead.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MAX_BYTES = 4_000_000        # only small JSON/NPZ artifacts are copied out of a run cache

LEGACY_CACHE_FILES = {
    "operating_point.json": "evidence/operating_point.json",
    "arm_results.json": "evidence/arm_results.json",
    "collar_sweep.json": "evidence/collar_sweep.json",
    "filter_results.json": "evidence/incumbent_filter_results.json",
    "union_results.json": "evidence/union_results.json",
    "buffer_derivation.json": "evidence/buffer_derivation.json",
    "residuals.npz": "evidence/oof_residuals.npz",
}

PROTOCOL = {
    "folds": "four equal spatial blocks (NW/NE/SW/SE) of the 3730x3292 competition grid",
    "buffer": "measured from residual autocorrelation, see evidence/buffer_derivation.json; the adopted "
              "collar is read from that file rather than restated here",
    "model": "HistGradientBoostingClassifier (200 trees, lr 0.08, 31 leaves) trained per fold on all "
             "catalogue pixels of the other three blocks plus 90,000 background samples",
    "excluded_features": "no catalogue-distance or SGMC-derived feature is used, so neither the "
                         "catalogue-gap nor the off-catalogue evaluation is circular",
    "truth_proxies": {
        "catalogue_gap": "held-out public catalogue pixels (60,988 px)",
        "off_catalogue": "USGS SGMC state-map fault cells more than 300 m from the public catalogue "
                         "(61,664 px) - the only populated fault population in reach that is "
                         "off-catalogue by construction, i.e. the population the competition scores",
    },
    "metric": "official distance-weighted Tversky index, alpha=0.2, beta=0.8, R=300 m triangular kernel, "
              "verified against a literal transcription of the published sums (scripts/check_metric.py, "
              "evidence/metric_check.json)",
    "claim_class": "COMPUTED on owner-mirror inputs; not organizer-authenticated and not a live score",
}

SUBMISSIONS = [
    {
        "id": "primary-h27-4-solo-d28",
        "name": "gemsdoe31-h27-4-solo-d28-20261004-8acb75e1",
        "role": "primary download - the best-scoring geometry this project has measured, re-emitted and "
                "re-validated here",
        "provenance": "re-emission of the dot set published as GEMSDOE28 "
                      "gems28-h27-4-r1-solo-d2-8-20261003-8acb75e1f2cc-nan.tif (owner mirror); pixel-identical, "
                      "freshly written and re-validated in this repository",
        "note_for_portal": "h27-4 r1 solo d=2.8 dot set (40199 px); owner-reported live 0.2708; "
                           "format re-verified against the competition grid template",
        "slot_approved": False,
        "why_not_slot_approved": "It is the incumbent, not an improvement. Nothing measured in this "
                                "repository beats it by a margin worth spending a weekly slot.",
    },
    {
        "id": "research-union-lidar-arm",
        "name": "gemsdoe31-union-b-p060-20261004-8acb75e1",
        "role": "research candidate - the strongest measured union on the off-catalogue proxy",
        "provenance": "the incumbent dot set plus every cell where the LiDAR-arm fold-OOF probability is "
                      ">= 0.60 and the cell is not on the public catalogue (scripts/run_union.py)",
        "note_for_portal": "incumbent h27-4 dot set + 65939 LiDAR-arm detections (p>=0.6, off-catalogue); "
                           "+0.0060 off-catalogue proxy DTI; research candidate",
        "slot_approved": False,
        "why_not_slot_approved": "The gain is measured on a proxy population (USGS SGMC state-map faults) "
                                "that resembles but is not the hidden expert-mapped truth, and no live "
                                "submission has tested it. It is the best-supported next-week candidate.",
    },
    {
        "id": "research-union-radiometric-arm",
        "name": "gemsdoe31-add-arm-d28-20261004-8acb75e1",
        "role": "research candidate - the radiometric half of the same union experiment",
        "provenance": "the incumbent dot set plus every cell where the radiometric+LiDAR fold-OOF probability "
                      "is >= 0.70 and the cell is not on the public catalogue",
        "note_for_portal": "incumbent h27-4 dot set + 15105 radiometric-arm detections (p>=0.70, "
                           "off-catalogue); +0.0017 off-catalogue proxy DTI; research candidate",
        "slot_approved": False,
        "why_not_slot_approved": "Same proxy caveat as the LiDAR union, with a smaller measured gain; kept "
                                "for the record because it is the variant that was built first.",
    },
    {
        "id": "legacy-d28-reference",
        "name": "gemsdoe31-reference-d28-offcat-44090-20261004",
        "role": "legacy audit reference (not recommended)",
        "provenance": "pixel-identical (not byte-identical) to the GEMSDOE25 D2.8 raster whose owner-reported "
                      "live score is 0.2600",
        "note_for_portal": "",
        "slot_approved": False,
        "why_not_slot_approved": "Superseded by the h27-4 geometry; kept only so the audit trail for the "
                                "owner-reported 0.2600 can be followed.",
    },
]


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def copy_legacy_cache(cache: Path) -> dict:
    copied = {}
    if not cache.is_dir():
        return copied
    for name, dest in LEGACY_CACHE_FILES.items():
        source = cache / name
        if not source.is_file() or source.stat().st_size > MAX_BYTES:
            continue
        target = ROOT / dest
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)
        copied[name] = {"path": dest, "bytes": source.stat().st_size}
    return copied


def inventory() -> list[dict]:
    rows = []
    for path in sorted((ROOT / "evidence").rglob("*")):
        if not path.is_file() or path.name in ("data_preparation.json",):
            continue
        rows.append({"path": str(path.relative_to(ROOT)), "bytes": path.stat().st_size,
                     "sha256": sha256(path)})
    return rows


def submissions_register() -> dict:
    receipts = {}
    for receipt in sorted((ROOT / "docs" / "downloads").glob("*-format-check.json")):
        receipts[receipt.name[: -len("-format-check.json")]] = json.loads(receipt.read_text())
    files = []
    for entry in SUBMISSIONS:
        receipt = receipts.get(entry["name"])
        if receipt is None:
            continue
        legacy = "validation" not in receipt          # receipts written before the convention split
        grid = receipt.get("grid", {})
        record = {
            "id": entry["id"],
            "name": entry["name"],
            "role": entry["role"],
            "provenance": entry["provenance"],
            "note_for_portal": entry["note_for_portal"],
            "slot_approved": entry["slot_approved"],
            "why_not_slot_approved": entry["why_not_slot_approved"],
            "positive_pixels": receipt.get("dots", grid.get("positive_pixels_inside")),
            "positive_pixels_on_public_catalogue": receipt.get("dots_on_catalogue"),
            "format_status": "locally validated against the grid template; not organizer acceptance",
            "receipt": f'docs/downloads/{entry["name"]}-format-check.json',
        }
        if legacy:
            legacy_file = str(receipt["file"])
            record["file_nan"] = legacy_file if "/" in legacy_file else f"docs/downloads/{legacy_file}"
            record["bytes_nan"] = receipt["bytes"]
            record["sha256_nan"] = receipt["sha256"]
            record["format_ok_nan"] = receipt["ok_to_upload_format_only"]
            record["hard_failures_nan"] = receipt["hard_failures"]
            record["organizer_acceptance_verified_nan"] = receipt["organizer_acceptance_verified"]
            record["legacy_receipt"] = True
        for short in ("nan", "allfinite"):
            validated = receipt.get("validation", {}).get(short)
            if validated is None:
                continue
            record[f"file_{short}"] = receipt["files"][short]
            record[f"bytes_{short}"] = validated["bytes"]
            record[f"sha256_{short}"] = validated["sha256"]
            record[f"format_ok_{short}"] = validated["ok_to_upload_format_only"]
            record[f"hard_failures_{short}"] = validated.get("hard_failures", [])
            record[f"organizer_acceptance_verified_{short}"] = validated.get("organizer_acceptance_verified", False)
        if "zip" in receipt.get("files", {}):
            record["zip"] = receipt["files"]["zip"]
        if "measured" in entry:
            record["measured"] = entry["measured"]
        files.append(record)

    union = ROOT / "evidence" / "union_results.json"
    if union.is_file():
        data = json.loads(union.read_text())
        for record in files:
            candidates = [row for row in data["unions"] if row["drop_catalogue_pixels"]]
            if not candidates:
                continue
            if record["id"] == "research-union-lidar-arm":
                best = max(candidates, key=lambda row: row["ff_DTI"])
                if best["dots"] == record["positive_pixels"]:
                    record["measured"] = {
                        "off_catalogue_proxy_DTI": best["ff_DTI"],
                        "incumbent_off_catalogue_proxy_DTI": data["incumbent"]["ff_DTI"],
                        "delta": best["ff_delta"],
                        "catalogue_gap_proxy_DTI": best["cat_DTI"],
                        "incumbent_catalogue_gap_proxy_DTI": data["incumbent"]["cat_DTI"],
                        "added_dots": best["added"],
                        "added_credit_per_dot": best["added_ff_credit_per_dot"],
                    }
            if record["id"] == "research-union-radiometric-arm":
                match = [row for row in candidates
                         if row["arm"].startswith("D_") and abs(row["threshold"] - 0.70) < 1e-9]
                if match and match[0]["dots"] == record["positive_pixels"]:
                    row = match[0]
                    record["measured"] = {
                        "off_catalogue_proxy_DTI": row["ff_DTI"],
                        "incumbent_off_catalogue_proxy_DTI": data["incumbent"]["ff_DTI"],
                        "delta": row["ff_delta"],
                        "catalogue_gap_proxy_DTI": row["cat_DTI"],
                        "incumbent_catalogue_gap_proxy_DTI": data["incumbent"]["cat_DTI"],
                        "added_dots": row["added"],
                        "added_credit_per_dot": row["added_ff_credit_per_dot"],
                    }

    primary = next((r for r in files if r["id"] == "primary-h27-4-solo-d28"), None)
    best_research = None
    for record in files:
        if record.get("measured") and record["id"].startswith("research"):
            if best_research is None or record["measured"]["delta"] > best_research["measured"]["delta"]:
                best_research = record
    return {
        "schema_version": 1,
        "generated_utc": "2026-10-04",
        "policy": "Every hash and pixel count below is copied out of the format-check receipt written by "
                  "scripts/build_submission.py. Local validation is not organizer acceptance and no file "
                  "here carries an organizer receipt.",
        "current_recommended": {
            "name": primary["name"] if primary else None,
            "role": primary["role"] if primary else None,
            "score_status": "owner-reported live 0.2708 for the underlying GEMSDOE28 artifact; no organizer "
                            "receipt exists in this repository",
            "slot_approved": False,
            "reason_not_slot_approved": "It is the incumbent, not an improvement: no measured candidate beats "
                                        "it by a margin that justifies spending the weekly slot.",
        },
        "best_research_candidate": {
            "name": best_research["name"] if best_research else None,
            "measured": best_research.get("measured") if best_research else None,
            "slot_approved": False,
        },
        "files": files,
        "format_conventions": {
            "nan": "finite values in [0,1] inside the footprint, NaN outside, nodata=nan - the convention "
                   "the official page specifies and the grid template uses",
            "all-finite": "every cell finite and in [0,1], zeros outside the footprint - a defensive "
                          "fallback; validated separately in src/gemsdoe31/submission.py",
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cache", default="/home/user/work/cache",
                        help="optional legacy run cache to copy small JSON/NPZ artifacts out of")
    args = parser.parse_args()

    copied = copy_legacy_cache(Path(args.cache))
    artifacts = inventory()
    summary = {
        "schema_version": 1,
        "generated_utc": "2026-10-04",
        "protocol": PROTOCOL,
        "legacy_cache_copied": copied,
        "artifacts": artifacts,
    }
    (ROOT / "registry" / "experiments.json").write_text(json.dumps(summary, indent=1) + "\n")
    register = submissions_register()
    (ROOT / "registry" / "submissions.json").write_text(json.dumps(register, indent=1) + "\n")
    print(f"registry/experiments.json: {len(artifacts)} artifacts inventoried, "
          f"{len(copied)} legacy cache files copied")
    print(f"registry/submissions.json: {len(register['files'])} files registered, "
          f"best research candidate {register['best_research_candidate']['name']}")


if __name__ == "__main__":
    main()
